### ISSUE TITLE
cannot find -lipasirglucose4

### ISSUE THREAD

**Issue by bhomaidan1990** [domschrei/lilotane#3]
Hi, I have tried the steps to build the planner, at the point of linking the `IPASIRSOLVER` I get the following Error:

```
[ 93%] Linking CXX executable test_arg_iterator
/usr/bin/ld: cannot find -lipasirglucose4
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/test_arg_iterator.dir/build.make:85: test_arg_iterator] Error 1
make[1]: *** [CMakeFiles/Makefile2:82: CMakeFiles/test_arg_iterator.dir/all] Error 2
make: *** [Makefile:95: all] Error 2

```
Tried `cadical`, and `riss` the same problem, while using `lingeling` I have got another error during the `cmake` stage 
```
cmake .. -DCMAKE_BUILD_TYPE=RELEASE -DIPASIRSOLVER=lingeling

CMake Error at CMakeLists.txt:34 (file):
  file failed to open for reading (No such file or directory):
    /Planners/lilotane/lib/lingeling/LIBS

-- Configuring incomplete, errors occurred!
```

**Comment by domschrei** [comment]
Hi, there were some small issues in the `CMakeLists.txt` which only occurred if the solver library was not built yet. It should work now.

**Comment by bhomaidan1990** [comment]
Thanks for your rapid reply, indeed that solved the problem.
