### ISSUE TITLE
Unable to acquire the paper

### ISSUE THREAD

**Issue by BKAUTO** [domschrei/lilotane#4]
Hi!

I think the link to the accompanying paper may has failed and I find no place to acquire the paper.
Thank you very much.

**Comment by domschrei** [comment]
Hi, I updated the references. [The main (JAIR) article about Lilotane](https://doi.org/10.1613/jair.1.12520) has just been published, I added it as a primary reference. It explains the approach in full detail and provides extensive evaluations whereas [the IPC planner description](https://dominikschreiber.de/papers/2020-ipc-lilotane.pdf) is of course just a brief outline of the planner.
